services:
  bitcoin:
    image: bitcoin/bitcoin:latest
    container_name: btc-node
    restart: unless-stopped
    volumes:
      - ${HOME}/data-bitcoin:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
    command:
      - "-printtoconsole"
    ports:
      - 18332:18332
      - 18333:18333

  pg:
    image: timescale/timescaledb:2.13.0-pg15
    shm_size: 512m
    command: postgres -c plan_cache_mode=force_custom_plan
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=indexer
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
  
  # indexer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: indexer
  #   ports:
  #     - 8080:8080
  #   links:
  #     - pg
  #   depends_on:
  #     - pg

volumes:
  pg: